services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      
  sqlserver:
    build:
      context: ./sqlserver
    container_name: sqlserver
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
